name: Build and Deploy via Docker Hub

on:
  push:
    branches: [ main, master ]

env:
  DOCKER_HUB_REPO: your-dockerhub-username/llm-query-system
  AZURE_CONTAINER_REGISTRY: bajazhackathonacr.azurecr.io
  CONTAINER_NAME: llm-query-system
  RESOURCE_GROUP: bajaj-hackathon-rg
  CONTAINER_APP_NAME: llm-query-system

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.DOCKER_HUB_REPO }}:latest,${{ env.DOCKER_HUB_REPO }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    # Note: Manual step required to pull from Docker Hub to Azure Container Registry
    # Run this locally after the build completes:
    # docker pull your-dockerhub-username/llm-query-system:latest
    # docker tag your-dockerhub-username/llm-query-system:latest bajazhackathonacr.azurecr.io/llm-query-system:latest
    # docker push bajazhackathonacr.azurecr.io/llm-query-system:latest
